rule("resources")
    after_build(function (target)
        local source_dir = path.join(os.projectdir(), "res")
        local destination_dir = path.join(target:targetdir(), "res")
        os.rm(path.join(target:targetdir(), "assets"))
        os.rm(destination_dir)
        os.cp(source_dir, destination_dir)
        os.rm(path.join(destination_dir, "xmake.lua"))
    end)
